---
# yaml-language-server: $schema=https://raw.githubusercontent.com/home-operations/kromgo/refs/heads/main/config.schema.json

gallery:
    enabled: true

badges:
  - id: talos_version
    query: node_os_info{name="Talos"}
    value: labels["version_id"]
    title: Talos version

  - id: kubernetes_version
    query: kubernetes_build_info{service="kubernetes"}
    value: labels["git_version"]
    title: Kubernetes version

  - id: flux_version
    query: label_replace(flux_instance_info, "revision", "$1", "revision", "(.+)@sha256:.+")
    value: labels["revision"]
    title: Flux version

  - id: cluster_node_count
    query: count(count by (node) (kube_node_status_condition{condition="Ready"}))
    title: Node count

  - id: cluster_pod_count
    query: sum(kube_pod_status_phase{phase="Running"})
    title: Pod count

  - id: cluster_cpu_usage
    query: round(avg(instance:node_cpu_utilisation:rate5m) * 100, 0.1)
    value: string(result) + "%"
    color: 'result <= 20.9 ? "green" : result <= 75.9 ? "orange" : "red"'
    title: CPU usage

  - id: cluster_memory_usage
    query: round(avg(instance:node_memory_utilisation:ratio) * 100, 0.1)
    value: string(result) + "%"
    color: 'result <= 20.9 ? "green" : result <= 75.9 ? "orange" : "red"'
    title: Memory usage

  - id: cluster_memory_usage_si
    query: avg(node_memory_MemTotal_bytes)-avg(node_memory_MemAvailable_bytes)
    value: humanSIBytes(result)
    title: Memory usage (SI)

  - id: cluster_memory_usage_base2
    query: avg(node_memory_MemTotal_bytes)-avg(node_memory_MemAvailable_bytes)
    value: humanBytes(result)
    title: Memory usage (base2)

  - id: cluster_uptime_days
    query: round((node_time_seconds - node_boot_time_seconds) / 86400)
    value: simplifyDays(result)
    title: Cluster Up Time

  - id: cluster_age_days
    query: round((time() - min(kube_node_created) ) / 86400)
    value: simplifyDays(result)
    title: Cluster age

  - id: ceph_health_status
    query: ceph_health_status
    value: 'result == 0.0 ? "Healthy" : result == 1.0 ? "Warning" : "Critical"'
    color: 'result == 0.0 ? "green" : result == 1.0 ? "orange" : "red"'

  - id: cluster_alert_count
    query: alertmanager_alerts{state="active"} - 1 # Ignore Watchdog
    color: 'result < 1 ? "green" : "red"'
    title: Alerts