---
# yaml-language-server: $schema=https://k8s-schemas-cjso.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name webhook-secret
  namespace: external
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name # name of created secret
    template:
      data:
        GITHUB_HOMEOPS_WEBHOOK_SECRET: '{{ .GITHUB_HOMEOPS_WEBHOOK_SECRET }}'
        GITHUB_QUBT_WEBHOOK_SECRET: '{{ .GITHUB_QUBT_WEBHOOK_SECRET }}'
        GITHUB_L1NKR_WEBHOOK_SECRET: '{{ .ITHUB_L1NKR_WEBHOOK_SECRET }}'
        GITHUB_QUBTTEMPLATE_WEBHOOK_SECRET: '{{ .GITHUB_QUBTTEMPLATE_WEBHOOK_SECRET }}'
        GITHUB_L1NKRTEMPLATE_WEBHOOK_SECRET: '{{ .GITHUB_L1NKRTEMPLATE_WEBHOOK_SECRET }}'
        GITHUB_QBUTDOCKER_WEBHOOK_SECRET: '{{ .GITHUB_QBUTDOCKER_WEBHOOK_SECRET }}'
        GITHUB_L1NKRDOCKER_WEBHOOK_SECRET: '{{ .GITHUB_L1NKRDOCKER_WEBHOOK_SECRET }}'
  dataFrom:
    - extract:
        key: github-webhook-secrets