---
# yaml-language-server: $schema=https://k8s-schemas-cjso.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.15.1
    digest: 'sha256:181bb834c1c041c872a5c7cfe72d201ae879503ec460c4463bdd7c16a41a5578'
  url: oci://ghcr.io/external-secrets/charts/external-secrets
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: ^https://token.actions.githubusercontent.com$
        subject: ^https://github.com/external-secrets/external-secrets.*$
