---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./gha-runner-scale-set-controller.yaml
  - ./gha-runner-scale-set.yaml
  - ./flux-operator.yaml
  - ./external-secrets.yaml
  - ./cert-manager.yaml
  - ./rook-ceph.yaml
  - ./rook-ceph-cluster.yaml
  - ./external-dns.yaml
  - ./grafana.yaml
  - ./kube-prometheus-stack.yaml
  - ./smartctl-exporter.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./descheduler.yaml
  - ./metrics-server.yaml
  - ./cloudnative-pg.yaml
  - ./dragonfly.yaml
  - ./onepassword-connect.yaml
  - ./spegel.yaml
  - ./k8tz.yaml
