apiVersion: v1
type: kubernetes.io/basic-auth
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namesapce: database
    labels:
        cnpg.io/reload: "true"
data:
    username: ENC[AES256_GCM,data:pFtMnPyEJLsev23n,iv:eHc0NvQGSnz/LwM2dw8pjCyaMScOHmkJO7/mMYayQWw=,tag:UZDS0t8vzXd9J2H2EuCI/w==,type:str]
    password: ENC[AES256_GCM,data:rsgvoCOW4dMhecrnkhU6hG0OxMcT98f+IHggKMIJzxkKwDfgTXJM,iv:R3c5VnbmIBue9Qs7CLoZTf21GTKXUqn2lcVEjr+F4Wk=,tag:E6JhMQ+xJdugSDKI5UjPfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqn46tdx7vazgkjuglseduk52plfrpz60zcqjqk83rfg8gwuv95qd4cem4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMEl3cUwyVENabk5KWnJC
            M2xlWkZoR3NmNDQrUlNwMHlidVp4UVFCaFVBCnYrUWZQM3dJUlFYZEE2VytOZG1w
            YW5wQ2M0VzdlNTVhM3VvYXhOcEsxNUUKLS0tIG1wUUlmTXgrY0thQ0ZWME1Qbnp0
            UkJ4RUpnOXN0LzFSZGE0MXE5Rm5TajQKIt31kaAGUc/3S4EaH+i4n3Pp2jnb0zUG
            jV+NnBKGDhNgFYqeX+e1GRTMJLHiBaAu6AcPmYaUurF+3MaqwiM5Jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-17T10:00:21Z"
    mac: ENC[AES256_GCM,data:Ra8uoi+Y04xOh6zXcmjgQaZeoZ8LQgOMikrZ6bS3zIxvhOSv2ZQ/bMTTo/xHsFUizpBlrv9AEvcHwpFEintdm1cPa7cd2qCTpJdFnOgbKYZlDbHSUta1h7Jc5uCuJPogh1pvF9+wx5b8o5zfqLp5BGjhtffebzaUj75iLB4NQxQ=,iv:5QqHM4Tr54Z9wvSVCkSGtb987bzz3LEnWzKcqaDmJkc=,tag:0lPrvsJ5NwfjU5B/y9lrdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
