apiVersion: v1
type: kubernetes.io/basic-auth
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: database
    labels:
        cnpg.io/reload: "true"
data:
    username: ENC[AES256_GCM,data:pSn/ZTr+rxuNEsQt,iv:u99OvcQuHRH7IiW8G4NS3Q3u5gJQAgCekQCDcyJvH7w=,tag:8pEi8zgpNSARQtOPaHgikA==,type:str]
    password: ENC[AES256_GCM,data:rZP+IyEnLbkmILCNPmMBzRuFYjenUD/zqYi77Q3rPxfWNdr+taDR,iv:OCIqbt4ed/voL5GZSDHRy3S1x2HlKKdv2aX1SC435m8=,tag:6+krva9d8NgjdBwf4X5p9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqn46tdx7vazgkjuglseduk52plfrpz60zcqjqk83rfg8gwuv95qd4cem4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4T0Z6ckgwWHlseDJyaG01
            TUg4QTJ0M0tNZy9XOVk3bVdLR3l5VVRXQXpBCjZwK0p6MlVVcVh6ajJVV0dzS1NI
            dGVmNjlORGxrMWdSVmtZYlNMbFRTYXMKLS0tIExPZit5RXRYZnhzekRLU1Qxeng0
            YnFMalVXOVRhU3hoblVtcTJoQ2xxK1UK2XMeS6t/ZRmtxuOLbXyHBhJ6dBOOE1eb
            5NJ0owVfSNwqAMv8E+wplRIM3uakjJTTn++bMwmDSeJHvdcyyXeDVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-17T10:23:13Z"
    mac: ENC[AES256_GCM,data:KLp2y3HoN+UkvMpQLnQD7lGu/yomwtjOCRIp85ACONb8X8HbBJhkqWiWNmWRhO73GE1OrBo5aoBd1/z4bmpgaZZXS5Qst61yyFdfMdEFUpHqamLA04xHM1EjsgVtQ7wuxjuXljCKxW6zzUJDoCxhlXCK0q+XA5rB/qYrAXCMpwk=,iv:Zu63fO0eHJXAvY+cmB+PH54zKAIDnHrJn0UCaoPXXJU=,tag:HJ2adPbRVQqcqhKCZSi1uw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
