apiVersion: v1
type: kubernetes.io/basic-auth
kind: Secret
metadata:
    name: gatus-user-secret
    namespace: database
    labels:
        cnpg.io/reload: "true"
data:
    username: ENC[AES256_GCM,data:1qYAItHb+EU=,iv:daqysFpGRuW0Y039g2th85MrrL1KUmwsNSsZAvSie5g=,tag:NWOm/Dmk8I2fGanWv9BVmw==,type:str]
    password: ENC[AES256_GCM,data:QuwInjz2wBfSwHjvHYfnBpY/twi3eHmuB6dq6lDx14qXgg2GtTPaFw==,iv:PtoSM8gdFp497syKLDlxVmw9aOwDwZcAAvsOzW/M6fU=,tag:fLXp5ZbNsGdj6dvjaPk4JA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqn46tdx7vazgkjuglseduk52plfrpz60zcqjqk83rfg8gwuv95qd4cem4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiY1pubTc0LzhyR2I2RUZp
            NW9MLy9yRHZNVHVIMTF5TWFxbWZMbURDUlRBCmE3dXRoTk5YMWJSaC9lbnJiVGRw
            aTZIRmI2enZmdTgyZnU3TVMyU1dLVkEKLS0tIFlPdThzSy82SVRRejl0Ni9NTzBV
            OGwvZG1LN1YwODE4VXN3OXlkdDQzMFUKR4HKC/jHGTNUylbl+YZ5hl3WWhv4mRxL
            OupiUd3pW75NeuGQ2Qg19P+qDUZUqLaaxpQ8DOrZwZCt0fUMsb15Ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-17T10:00:33Z"
    mac: ENC[AES256_GCM,data:0lK/By7jEnZNdilarpx8HxeOlctE2g+LLukIuQlJAe/GbCNCDBz+Miphz7n40NflUqsS7fidj9RvR+LpsO0H89GHBqWW5CJKcJvl+DfyCovdEkVLd0tsYbaWFMWusHo0Rcwl/btpNWjjCEI2XXFZ3+jDlwvJmYCU3eEqXZj83vw=,iv:dtPbdZsDxk9nNZYu6CFVQdVtpp9rKOPAE3Dggtxf64k=,tag:/wXAaPOh2yw01TWbUzdRKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
