---
# yaml-language-server: $schema=https://k8s-schemas-cjso.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  type: oci
  interval: 2h
  url: oci://ghcr.io/controlplaneio-fluxcd/charts
