---
# yaml-language-server: $schema=https://k8s-schemas-cjso.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: onepassword-connect
  namespace: flux-system
spec:
  interval: 2h
  url: https://1password.github.io/connect-helm-charts
