---
- id: github-chrede88-renovate
  execute-command: /config/renovate-operator.sh
  pass-arguments-to-command:
    - # job name
      source: string
      name: chrede88
    - # namespace
      source: string
      name: renovate
    - # project
      source: payload
      name: repository.full_name
    - # Renovate Operator webhook URL
      source: string
      name: http://renovate-operator.renovate.svc.cluster.local:8082
  trigger-rule:
    and:
      - # Validate the webhook secret
        match:
          type: payload-hmac-sha1
          secret: >-
            {{ getenv "GITHUB_HOMEOPS_WEBHOOK_SECRET" | js }}
          parameter:
            source: header
            name: x-hub-signature
      - # Trigger only for chrede88 user
        match:
          type: value
          value: chrede88
          parameter:
            source: payload
            name: repository.owner.login
      - or:
        - # Trigger on Renovate Dashboard issue
          and:
            - match:
                type: value
                value: issues
                parameter:
                  source: header
                  name: x-github-event
            - match:
                type: value
                value: edited
                parameter:
                  source: payload
                  name: action
            - match:
                type: value
                value: open
                parameter:
                  source: payload
                  name: issue.state
            - match:
                type: value
                value: Renovate Dashboard
                parameter:
                  source: payload
                  name: issue.title
        - # Trigger on GitHub Pull Request edits
          and:
            - match:
                type: value
                value: pull_request
                parameter:
                  source: header
                  name: x-github-event
            - match:
                type: value
                value: edited
                parameter:
                  source: payload
                  name: action
            - match:
                type: value
                value: open
                parameter:
                  source: payload
                  name: pull_request.state
            - match:
                type: value
                value: bb-17[bot]
                parameter:
                  source: payload
                  name: pull_request.user.login