---
# yaml-language-server: $schema=https://json.schemastore.org/helmfile
repositories:
  - name: cilium
    url: https://helm.cilium.io

releases:
  - name: cilium
    namespace: kube-system
    chart: cilium/cilium
    version: 1.17.2
    values: ['../../kubernetes/apps/kube-system/cilium/app/helm-values.yaml']
    wait: true
