---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orbital-sync-config
  namespace: network
data:
  PRIMARY_HOST_BASE_URL: "http://pihole-0.pihole.network.svc.cluster.local"
  SECONDARY_HOST_1_BASE_URL: "http://pihole-1.pihole.network.svc.cluster.local"
  SECONDARY_HOST_2_BASE_URL: "http://pihole-2.pihole.network.svc.cluster.local"
  SECONDARY_HOST_3_BASE_URL: "http://10.10.30.60"
  INTERVAL_MINUTES: "30"
