---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: kubernetes-folder
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  title: "Kubernetes"
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: flux-folder
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  title: "Flux"
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: ceph-folder
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  title: "Rook-Ceph"
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: unifi-folder
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  title: "Unifi"
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: envoy-folder
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  title: "Envoy"
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: nodes-folder
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  title: "Nodes & Drives"
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: cilium-folder
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  title: "Cilium"
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: database-folder
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  title: "Database"