creation_rules:
  - path_regex: cluster/talos/config/talsecret(\.sops)?\.ya?ml
    input_type: yaml
    encrypted_regex: ^(cluster|secrets|trustdinfo|certs)$
    age: age1nqn46tdx7vazgkjuglseduk52plfrpz60zcqjqk83rfg8gwuv95qd4cem4
  - path_regex: cluster/talos/.*.ya?ml # Talos config
    input_type: yaml
    encrypted_regex: ^(token|crt|key|id|secret|secrets|secretboxEncryptionSecret|ca)$
    age: age1nqn46tdx7vazgkjuglseduk52plfrpz60zcqjqk83rfg8gwuv95qd4cem4
  - path_regex: cluster/kubernetes/.*.ya?ml # Kubernetes secrets
    input_type: yaml
    encrypted_regex: ^(data|stringData)$
    age: age1nqn46tdx7vazgkjuglseduk52plfrpz60zcqjqk83rfg8gwuv95qd4cem4

stores:
  yaml:
    indent: 2
