apiVersion: v1
kind: Secret
metadata:
  name: onepassword-token
  namespace: external-secrets
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:74Ms5pF3xu65bTgx85vkLhoNoV1WSmqxtRh9BtAoQDcnDXM2ZKRXBscLi2FKcK4rFwYJPoJfzdaQ+ysGaSr7w4cYU84qgT37pWBhAi3vh9rvgRbTt3G320wRo2l01sPejs/mckn4TVNSFbdMFab+tyAEtlMFSyMZw/g5nXj47JzkPP9JCXQFw/AJIkW/xuGZ665rVSvfu6nNrqGxIFc2qOBky79+hElSBJ//g7lIHASr+qscXy1L1yUPCI2jPXe14IfIFmYFeTeUjtxTSAiRbrXSXS+Iw+FcuHEeuaaB04Y4VCbYFr+KWvduQep5p6nd3xDvfTRwS8uMVg4aezHnFhkZk3p7SXYhwXOA/MTyiso4H0Mud6n7UDXDBkGdJRVeuQzt/zfJbSMmDteTrfjN1r0lmZgM5lO4zuj02mP3tP9EMFzom7+RxfRT8Mjm5uxWsDpYZV6z5fgIiqBCO3pGve+p7C/s1iZN+f5D6vViTB7kpqqX5PTsSZb7XukoInG3i0nDVZ5VxSHEYD5BTlex8ee6S7hOOEgj73dlT+0ejd7SX6GoV7YsVlkmnrpO+9Ic05J/qpn9Yfm2YuqbcHPd2/inKCJpGoO077ZapNZxYYCIbXktrcJ2+l69dh1bRjZUK/7fqxn597K8dW1AvxLoC+L1EmWRXo39mnmje1vGj8+pDWveAErjkVMCHCod08qunpSqfYfyV7w/RtIm1g7Hl0Ds6zCwFoW+Sl46XGc6k7pEuGtyzGnr/Wp2+kqw3Ty4Y7klaRyJZ9TAd5Rf7SgwRcq3FBi9OQAF/gAtj6+5Pr6/BUyGNus4gcyRC7R+m0v2+snEStlj9G1wnz53iFvVm9R3,iv:Zmkp15fGLi4aBzToxpoGZiUQ8cjfHN0K7YUt+IM3cTA=,tag:2xvMFVrL55yOttJGiln3jw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nqn46tdx7vazgkjuglseduk52plfrpz60zcqjqk83rfg8gwuv95qd4cem4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyY1NLZ1ljdk1JZzFWK2RO
        OGtjTzZnQ2ZjK2ZvTDIwcDdkcXhhT3FaVGhFCnNHa2JUenJXeFpXYmU5YWpxQ1RQ
        YlhmUTlMeEgvYWRLbDM1R2VwZFpUUDQKLS0tIDdQeWVPYURNaEMzR05oa3pDYit6
        V2l2R2Jva012NzhvakRXOGpnbkZpRlkKUHiT3G1UxiHwnR5OLWdh+wUhzGj77RU4
        QO0/ARGbFQZkHc8687ucdY05luVqg8rvqkua9XeVXeKlHsqTRT/rVw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-03T18:36:20Z"
  mac: ENC[AES256_GCM,data:Ck+LLG5sUQ8lenTOub3iMEzdKHJwFMjUlcfpcWfmDWPWRc1YlR9SidRj13XOFpoBv8YZ0Y8zTVJBNls4GmSUBbgaGWg0bmCYMDOqen1O4oqjQlOwfxl8ClQu7sgYTqiHIx/OHhzHPfjyQ6x0RQ5GpXZSvNGvAOzQTcIZqN57oew=,iv:syUhUPrdAXE0tbG2br98g3gjDnfBMys4CDvKoBfWGw8=,tag:deeSp/hFP2QGSADGJEgedw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
