apiVersion: v1
kind: Secret
metadata:
  name: onepassword-token
  namespace: external-secrets
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:G/tupzVNCndEIxC/1H9lPi6UQcryIq9u52vNM7nfLGvRI2OD+JdHlkTTpKH+SjRHmYKk2pQeYoXY4PWRnEbkK82XMWwaHY7bFLTNjDBejlYK8qaW7crTGB1IU7tne7mea1kqD6s8zJg2L6sQUBGFH7nKKafng0OsvbGY5lXgqxnr/esGgzVNxa2YWc4w5NA0ZMT2dM5/AKb6pdlpkNGYDrQ41JKb7fPoBjXozOZaBkCaHDueidquv+QPhgdBswuvkJvuF6milTHys5P9RLHVIfLmQV2NOpcGfU44xtcqDrEbuWbkAOvcdObv5bZ0FkAcO+/5j63D1rxKqlWqFvmSyaP7A5ZwZhfmd40B+rbAPu3By6yvqYoGiJQn1DUZHvJGHSHyYYRkJc3aykgxewJ8LtvfBstm9RevvUf3bvxfDeiS4ZIpLSYz+NF+GKW0ka9tn/B9c785IiLf2lQnbbaS908/yzNoo3AClOmz+OZRjtk5JyK/zkQPLh0iQy2GX4zbSSxCdEzxyI6NLx2yyzVsIZ4SBsRUkWSsBjSkznlZmhlFM1KDwpaMeGmqC4Xmpw8NSO1u39gCjoypQUsmeSnC9LHhXoOHfdSCAjNCPSspn7DYfvb3qxsaEtuO+O/Jbdf88MZwr8Dz1/6UJk8PrJcYKG/5p6SWchaV5Pm0wcs7NdJK1A04VGrSVWowJOvLBr+vc8NeN1Y16hYHnG17R0IUUzjzdah2QT6DrPlzyHgtJJIW/gJn2S4+dWZWVG/QogCoYSlOhMfUEk7kiHyAW1duUsrpJ+bq6dUR+EEzLKjYKETqrzfiOhuUrlAE2AY51qmmxe9Ppl58OBNxB+/fVfxGBs6J,iv:KtUggERyH4FpJTPHhEW86KZ2a5DrBScE4OYkRw/isis=,tag:GALzSe1DNX/2klE0wL2j1A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nqn46tdx7vazgkjuglseduk52plfrpz60zcqjqk83rfg8gwuv95qd4cem4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVXh6N2lpZUdtMmsvUWsw
        ZC9ucE04RkRZQUZkdi9McHlKWHZjb3RTL1hvClgvR0xna2pNQnRlUEdEcndlVldt
        WTJiOHozaHVFYVVNNmkxS0VBYklQZFkKLS0tICtEZGFDVHBsRWpDY3F5Szl5ZlR6
        dGRXRXdVK0x5ZnAzdzBrODQxUy9rRGcKUjhKNbrVdHgIJaIMA0Z8RbMVS614iexF
        eXUK79Pm49cRmJYce6AEO+VV7jkktsPt65KFAk46H/YoiH6lwqwtng==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-01T20:58:13Z"
  mac: ENC[AES256_GCM,data:xWKNzXc3/1T6XYKsnDlxoRxYuueMAkao6XDuVuMzIMAeckmJnc5vmfT8FH9LFJgwNpFsM2QDKEEd9gEbyQmo79kEeKViHrBOHRo02ju4DQdWnDBD8fmwpioz7q8QSqihc2Qpmlqcy7V75f6SF9vyIb26gnoHbmyajGM4Jfs6MZg=,iv:CvfpfhZeTO34hGa7zjLt2cfPvFX8YnfG2WRtQaDTE+0=,tag:nqtE0wg48cR8VqkaMX12lQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
