apiVersion: v1
data:
    flux.agekey: ENC[AES256_GCM,data:7McUfBaMqS564xm9Mpzv6lptH98R9beRul9PFFnk4P2ccT0hU/beISwfx/20WMjxyNqmdh/8jKRdK2cSxLq/C8WeZjNTMU3sHXzQMcg/kyB0GE3KoC31PB41CeB0EFl7e/xwGyUxl+VM2YtB1+hi14QicQ7p9nEJuqiREHTdqtF7+M0L/yg/djyRp2zQyak94Vej+rBWpxOOZ5a8e/asO9qZ1cY+bZExojK7fSNkXdLBqMfVTchBSMqkRGt8OSOq67Z4XOLnb6WMWjJIItmtriV8fr9niIZ51DSWNCjnpmXQ2hBMi2cf8eBifvr/4THUXX/tSMoFt1aO2u9P,iv:iKMf8qnFuqz5Kt8YLnZwPaqpDnPeQ7WlcRquyLEFa5Y=,tag:C3s44+KFBSjzpi4XjTSsxQ==,type:str]
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqn46tdx7vazgkjuglseduk52plfrpz60zcqjqk83rfg8gwuv95qd4cem4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjb3NTU0EyNGJHRGhOR1c3
            amtHTmdxOGZjbWpjaktiMThmL2FWMmJEcFhJCnFBNG5pejNDdGZ2N3FEWXpXOTRI
            L2xTNTdJS055SUEyNm1HYVYyN2tQZWcKLS0tIC9sckNVZUYrd1hYQk1mbDJQZ3pi
            cERyMCt6ZTZnc2c0c1VzY0FZTE9EWFUK86gKdWvMd+B4Ges2vI8EHgHVuiJNUUHK
            9EZFU6uloEY4xVB5mKoAyX5gutfeEP9L1h2UqLWMMY/QvdaHzDFfRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-29T18:36:34Z"
    mac: ENC[AES256_GCM,data:q9XDwrQlf+gYMUgbJauiu0/crqypYlZcujwo7ofpTZdlLPdvhtnqSe1HQ+GJjsp2obIj/eq8fLUD2JQ13HdGOpzBEqb0hH0DMnZTa9/bIzDYbJ2CcNuvHjg7DDwZQjPCokrJYPRKae20aVpB/YUk5mvnRIMTBk6LB3EX7aeWGBA=,iv:yf25VCP9AUG99pPbatqKMBeiyxhoUpP9/GszBLx3UWw=,tag:HYD1yRw8BalECYJQ7BYa+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
