apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
data:
  api-token: ENC[AES256_GCM,data:vft7VTI9Z/cEU/o31EOle2s34bzDSLGYbo55W63PuPovj9pUL2kfOvxEWBkr85FrV+nOI5bVb/E=,iv:/Ih4JRDKeiSTvwZI8TPxHcFZqA8J4aPLnnKEWIj9/dU=,tag:/BZHMKOFNZZnbWpitrb+CA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nqn46tdx7vazgkjuglseduk52plfrpz60zcqjqk83rfg8gwuv95qd4cem4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSU3BzdlRWOXZWcFJJSGtU
        cXFOMzNYUUlPMHVJMXZCQ3ZHSDRPeGNqSnl3CnY1eEdZS2p4R2FzdSt4SHJpYStT
        dzlqcmNLT3d3eGl0NDhmU1ByUGRNSGsKLS0tIDFqaGhaNkhRSjdYekhxYjNibVdJ
        UXAzZHhIV1l2aGpmZFQrU296NkZiNTAKokfghNbI2eU1O+BPDyaOXzXtdUHBU0cQ
        LXKB6BgQAyx0W7ZHfKVCKH+OTBsm251tvwXM5hId9HAaDw09cCGTNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-21T20:47:34Z"
  mac: ENC[AES256_GCM,data:kQMAKR4E6Na5/7YM+8HBFvp/cWG6lfTFvgwwvnrqwqHv+sfvRWsWg8je9LY12dclNo9fp4Ldjy+m42KxkuxH9+hJKF+ml37wGqOGfpYwa6MEX5TMdwDISKJQq93vGJ19MsGxnZzyOsc+qznYB8bWf9Ot0fDBLzC+cDU/rCSXGIQ=,iv:4gHIE4Knmz5eqwHkaJ+CS76LzW0B3CFFJHnwtj3K7jg=,tag:ef757xzh+v8NNdwVAkaTEA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.3
