apiVersion: v1
kind: Secret
metadata:
    name: ghcr-secret
    namespace: external
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:SkMEsTU7p141ApVfTvpShvl31GcGvquyum/aw9IPOTIWblQomiaf8ChtWFLPSJDiXYbS0O6kcchZolxc93Gt64aOzKnfOH/a9BnOG1i+RkXMocddR0oIGA4os1STlqTx5PbIfFsmIv6yMb0s8Ry40Arf5I2AWJrLn5tCU1C9ryb2zQO582UYVA==,iv:j1iN+tvcJofToCf09KE0kNdXpZPaunMD9ehvJuj37U0=,tag:lzHfuf7DgA1NMG++87BPfg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqn46tdx7vazgkjuglseduk52plfrpz60zcqjqk83rfg8gwuv95qd4cem4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETkhqTFhQd2RxM0xDK0V4
            YUtENzVNWW1wUjNNaXVpWEpSVTlRMkdPclE4Cld0Mm9BV0t6VCtHS3ZOa1VOTFNO
            ZHI4TDNaSzIyS3pKSEs1U2tVbHc3Z1EKLS0tIG5YZjl0Qzl2d2paUjVLcXA5SC9M
            dUhSc0RoWE8zcWVOeFgvMFdlMGdkN00KTazTryGU8TwYDOorr1tWhScPHlGC8VzL
            +014rswhXWh2oRUUHn7CmvaLvdzN63RywLvKEfB1zmAAx6r8wi0Yww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-10T20:49:35Z"
    mac: ENC[AES256_GCM,data:fB6JiZfRkpzOGS2+n0bZwFri3/ReFrVxBz+C0ysLX+iQR7wkcMIc+wZgTkkOV1JZXmsbqWQ9IDZlaQAw5d8mhtr3LIpmYMiBuMpkljUSehNRL0U0mhwoGyxzVwVe45zs0wXLuFiX2mxVP1hSI3MIF/VaQU9cVYvf8+lMje8IlFM=,iv:K2KEOuTXDy+OoTAJZYMIoYsRG5dpYdNccQpMAcxg3Gs=,tag:ijqk9jL3Gy2UqC0YGOBLmQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
