---
# yaml-language-server: $schema=https://k8s-schemas-cjso.pages.dev/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: qubt
  namespace: external
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: app
      app.kubernetes.io/instance: qubt
      app.kubernetes.io/name: qubt
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
