---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: &name qubt
  namespace: external
spec:
  selector:
    matchLabels:
      app: *name
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
