---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: internal
  labels:
    app: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Cjso Homepage

    theme: dark
    color: slate

    useEqualHeights: true

    layout:
      Network:
        header: true
        style: row
        columns: 2
      DNS:
        header: true
        style: row
        columns: 4
      Observability:
        header: true
        style: row
        columns: 3
      Storage:
        header: true
        style: row
        columns: 2
      Other:
        header: true
        style: row
        columns: 3
  services.yaml: |
    - Network:
        - Unifi:
            icon: unifi.svg
            href: https://10.10.0.1/
            description: Unifi Network Application
            widget:
              type: unifi
              url: https://10.10.0.1
              username: "{{HOMEPAGE_VAR_UNIFI_NETWORK_USERNAME}}"
              password: "{{HOMEPAGE_VAR_UNIFI_NETWORK_PASSWORD}}"
    - DNS:
        - Pihole0:
            icon: pi-hole.svg
            href: https://pihole.local.cjsolsen.com/admin
            description: pihole-0
            widget:
              type: pihole
              url: http://pihole-0.pihole.network.svc.cluster.local
              key: "{{HOMEPAGE_VAR_PIHOLE0_API_KEY}}"
        - Pihole1:
            icon: pi-hole.svg
            href: https://pihole1.local.cjsolsen.com/admin
            description: pihole-1
            widget:
              type: pihole
              url: http://pihole-1.pihole.network.svc.cluster.local
              key: "{{HOMEPAGE_VAR_PIHOLE1_API_KEY}}"
        - Pihole2:
            icon: pi-hole.svg
            href: https://pihole2.local.cjsolsen.com/admin
            description: pihole-2
            widget:
              type: pihole
              url: http://pihole-2.pihole.network.svc.cluster.local
              key: "{{HOMEPAGE_VAR_PIHOLE2_API_KEY}}"
        - PiholeBackup:
            icon: pi-hole.svg
            href: http://10.10.30.60/admin
            description: backup pihole
            widget:
              type: pihole
              url: http://10.10.30.60
              key: "{{HOMEPAGE_VAR_PIHOLE3_API_KEY}}"
    - Observability:
        - Grafana:
            icon: grafana.svg
            href: https://grafana.local.cjsolsen.com
            description: Grafana
            widget:
              type: grafana
              url: http://grafana.observability.svc.cluster.local
              username: "{{HOMEPAGE_VAR_GRAFANA_USER}}"
              password: "{{HOMEPAGE_VAR_GRAFANA_PASSWD}}"
        - Gatus:
            icon: gatus.svg
            href: https://gatus.local.cjsolsen.com
            description: Gatus
            widget:
              type: gatus
              url: http://gatus-web-svc.svc.cluster.local
        - Prometheus:
            icon: prometheus.svg
            href: https://prometheus.local.cjsolsen.com
            description: Prometheus
            widget:
              type: prometheus
              url: http://kube-prometheus-stack-operator.observability.svc.cluster.local:443
    - Storage:
        - Ceph:
            icon: ceph.svg
            href: https://ceph.local.cjsolsen.com
            description: Ceph Dashboard
    - Other:
        - GitHub:
            icon: github.svg
            href: https://github.com/chrede88
            description: My Github Repo
        - Website:
            icon: https://raw.githubusercontent.com/chrede88/k3s-cluster/main/cluster/home/homepage/icons/cjso.svg
            href: https://cjsolsen.com
            description: Main Website
        - LinkTree:
            icon: https://raw.githubusercontent.com/chrede88/k3s-cluster/main/cluster/home/homepage/icons/cjso.svg
            href: https://l1nkr.cjsolsen.com
            description: Linktree Website
  widgets.yaml: |
    - resources:
         cpu: true
         memory: true
         disk: /
         
    - search:
        provider: duckduckgo
        target: _blank

    - datetime:
        text_size: xl
        format:
          timeStyle: short
  bookmarks.yaml: ""
  docker.yaml: ""
  custom.css: ""
  custom.js: ""