---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: it-tools
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      it-tools:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/it-tools
              tag: 2024.10.22@sha256:7f26ae8d7a4a58b8d70b685cba5cbaa54d7df876d9f8bae702207f45b06d9b7c
            resources:
              requests:
                cpu: 5m
                memory: 32Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ['ALL'] }
        pod:
          securityContext:
            runAsUser: 3145
            runAsGroup: 314
            fsGroup: 314
            fsGroupChangePolicy: 'OnRootMismatch'
    service:
      app:
        ports:
          http:
            port: 8080
    persistence:
      tmpfs:
        type: emptyDir
        advancedMounts:
          it-tools:
            app:
              - path: /tmp
                subPath: tmp
