---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-secret
  namespace: internal
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: test-secret # name of created secret
    template:
      data:
        secretKey: '{{ .password }}'
  # OR
  dataFrom:
    - extract:
        key: testK8s # 1p item name
