# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: unpoller
#   namespace: flux-system
# spec:
#   targetNamespace: observability
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: unpoller
#   dependsOn:
#     - name: kube-prometheus-stack
#   path: ./cluster/kubernetes/observability/unpoller/app
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   wait: false
#   interval: 30m
#   retryInterval: 1m
#   timeout: 15m
#   decryption:
#     provider: sops
#     secretRef:
#       name: sops-age