---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.32.2/namespace-v1.json
apiVersion: v1
kind: Namespace
metadata:
  name: database
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
