---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name forgejo-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        email: "{{ .email }}"
        ssh_host_ed25519_key: "{{ .ssh_host_ed25519_key }}"
  dataFrom:
    - extract:
        key: forgejo
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name forgejo-signing-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        ed25519.pub: |
          {{ .ssh_host_ed25519_key }}
  dataFrom:
    - extract:
        key: forgejo
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name forgejo-db-passwd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        dp_passwd: "{{ .password }}"
  dataFrom:
    - extract:
        key: forgejo-cluster-user-secret