---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./qubt/ks.yaml
  - ./l1nkr/ks.yaml
  - ./kromgo/ks.yaml
components:
  - ../../flux/components/alerts
