---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./qubt/ks.yaml
  - ./l1nkr/ks.yaml
  - ./kromgo/ks.yaml
components:
  - ../../flux/components/alerts
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: not-used
      namespace: cert-manager
    unsetOnly: true
