---
# yaml-language-server: $schema=https://k8s-schemas-cjso.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: external-secrets
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    installCRDs: true
    replicaCount: 1
    leaderElect: true
    image:
      repository: &repo ghcr.io/external-secrets/external-secrets
    webhook:
      image:
        repository: *repo
      serviceMonitor:
        enabled: true
        interval: 1m
    certController:
      image:
        repository: *repo
      serviceMonitor:
        enabled: true
        interval: 1m
    serviceMonitor:
      enabled: true
      interval: 1m
