---
# yaml-language-server: $schema=https://k8s-schemas-cjso.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app rook-ceph
  namespace: flux-system
spec:
  targetNamespace: &namespace rook-ceph
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: rook-ceph-operator
      namespace: *namespace
  path: ./cluster/kubernetes/apps/rook-ceph/rook-ceph/app
  prune: false # never deleted
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://k8s-schemas-cjso.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app rook-ceph-cluster
  namespace: flux-system
spec:
  targetNamespace: &namespace rook-ceph
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: rook-ceph-cluster
      namespace: *namespace
    - apiVersion: ceph.rook.io/v1
      kind: CephCluster
      name: rook-ceph
      namespace: *namespace
  healthCheckExprs:
    - apiVersion: ceph.rook.io/v1
      kind: CephCluster
      failed: status.ceph.health == 'HEALTH_ERR'
      current: status.ceph.health in ['HEALTH_OK', 'HEALTH_WARN']
  dependsOn:
    - name: rook-ceph
  path: ./cluster/kubernetes/apps/rook-ceph/rook-ceph/cluster
  prune: false # never deleted
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://k8s-schemas-cjso.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: internal-rook-ceph-ingress
  namespace: flux-system
spec:
  targetNamespace: &namespace rook-ceph
  commonMetadata:
    labels:
      app.kubernetes.io/name: internal-ingress
  healthChecks:
    - apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      name: ceph-dashboard
      namespace: *namespace
  healthCheckExprs:
    - apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      failed: status.parents.conditions.filter(e, e.type == 'Accepted').all(e, e.status == 'False')
      current: status.parents.conditions.filter(e, e.type == 'Accepted').all(e, e.status == 'True')
  dependsOn:
    - name: cilium-crd
  path: ./cluster/kubernetes/apps/rook-ceph/rook-ceph/ingress
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
