apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    namespace: observability
type: Opaque
data:
    admin-user: ENC[AES256_GCM,data:ShDGNv7bFj8=,iv:wG+0PEovWLcG+HwAhOA6JWZN63p4WbLQ7A6WJzMEkOw=,tag:/I/ayxF3S9Qjlnq8WWitgQ==,type:str]
    admin-password: ENC[AES256_GCM,data:SSTauTVM07b0+k1YV96ltncq7eHUrLUU+lVo9zhEKNuV+9u9IbeEvPfoT/2X9Jq2Dcw5e3LzhcI=,iv:DgvFbkX2KbVdEPObk7QNHoHpvsPe75UwrFU0TqExwL0=,tag:KEja6iEsvNvXaSn4qE6ysA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqn46tdx7vazgkjuglseduk52plfrpz60zcqjqk83rfg8gwuv95qd4cem4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWDRvWUJKZTVERnhmLzZl
            S2h0YnBXRjFYT3M2YUQwTmhIT1oyMFU4Q1VRCm5xbnhRR1Q4elptSmtjZkowYU40
            eWVaNXhmOVIxVjByR3hhQnhSQUJHMWsKLS0tIEpXNGl4a2twTXg3ZzY3YjhoR2Mv
            Wnp4VkhBQm5ZVHhYRTMwcCtjN1I5S2cKkpXqygjy4Bp+2S2bZC3Y4HL4HfGbYB7I
            n9QKSbreccXm5AMVm40G9EzWrAFUWcM7Z2xi1UKzlvHcrFviHq+Dtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-02T20:27:20Z"
    mac: ENC[AES256_GCM,data:Ot2tUMr21zsknjBBUlztpBMXuXC8rkuvaeXNGzH2Sm4dGbYn8LCT5yDX6bAZ6spAC+gVoBe9u3yE7hwd9lXJ1WZEqSQfylCQqoywCFk3O84jwrf7eQbOAcW9ExSamCIPaI0H7LqbkkrefL3QxrE9qSDs+AzQvxrpWBjBDV78Cbo=,iv:BgqhAU6Uce5gglpzLdn4uD0qHZn+oI4igZgMLuDr110=,tag:8gtOe7MpKzbABlBGbmf3rA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
