---
# yaml-language-server: $schema=https://k8s-schemas-cjso.pages.dev/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: external-gateway
  namespace: network
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  gatewayClassName: cilium
  addresses:
    - type: IPAddress
      value: 10.10.30.72
  listeners:
    # catch all external http -> https
    - name: http-redirect-external
      hostname: '*.cjsolsen.com'
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    # catch traffic for kromgo
    - name: kromgo
      hostname: kromgo.cjsolsen.com
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              external-gateway-access: 'true'
      tls:
        mode: Terminate
        certificateRefs:
          - name: kromgo-cjsolsen-com
    # catch traffic for qubt website
    - name: qubt
      hostname: cjsolsen.com
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              external-gateway-access: 'true'
      tls:
        mode: Terminate
        certificateRefs:
          - name: qubt-cjsolsen-com
    # catch traffic for l1nkr website
    - name: l1nkr
      hostname: l1nkr.cjsolsen.com
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              external-gateway-access: 'true'
      tls:
        mode: Terminate
        certificateRefs:
          - name: l1nkr-cjsolsen-com
