---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  - ./slack-token.yaml
  - ./notifications.yaml
  # Flux-Kustomizations
  - ./kube-prometheus-stack/ks.yaml
  - ./grafana/ks.yaml
  # - ./unpoller/ks.yaml
  # - ./kromgo/ks.yaml