---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    pod-security.kubernetes.io/enforce: privileged
    internal-gateway-access: "true"