---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./configmap-pihole.yaml
  - ./pihole-password-secret.yaml
  - ./dns-service.yaml
  - ./headless-service.yaml
  - ./dashboard-service.yaml
  - ./statefulset-pihole.yaml
