---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: &name pihole
  namespace: network
spec:
  selector:
    matchLabels:
      app: *name
  serviceName: *name
  replicas: 3
  template:
    metadata:
      labels:
        app: *name
    spec:
      containers:
        - name: *name
          image: pihole/pihole:2025.02.0
          envFrom:
            - configMapRef:
                name: pihole-configmap
            - secretRef:
                name: pihole-password
          ports:
            - name: svc-80-tcp-web
              containerPort: 80
              protocol: TCP
            - name: svc-53-udp-dns
              containerPort: 53
              protocol: UDP
            - name: svc-53-tcp-dns
              containerPort: 53
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     port: svc-80-tcp-web
          #   initialDelaySeconds: 60
          #   periodSeconds: 10
          #   successThreshold: 1
          #   timeoutSeconds: 15
          volumeMounts:
            - name: pihole-etc-pihole
              mountPath: /etc/pihole
            - name: pihole-etc-dnsmasq
              mountPath: /etc/dnsmasq.d
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: *name
  volumeClaimTemplates:
    - metadata:
        name: pihole-etc-pihole
        namespace: network
      spec:
        storageClassName: ceph-block
        volumeMode: Filesystem
        accessModes:
          - 'ReadWriteOnce'
        resources:
          requests:
            storage: 3Gi
    - metadata:
        name: pihole-etc-dnsmasq
        namespace: network
      spec:
        storageClassName: ceph-block
        volumeMode: Filesystem
        accessModes:
          - 'ReadWriteOnce'
        resources:
          requests:
            storage: 3Gi
