---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./cilium/ks.yaml
  - ./metrics-server/ks.yaml
  - ./descheduler/ks.yaml
  - ./irqbalance/ks.yaml
components:
  - ../../flux/components/alerts
