apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name qubt-caddy
  namespace: internal
  labels:
    app: *name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *name
  template:
    metadata:
      labels:
        app: *name
    spec:
      containers:
      - image: ghcr.io/chrede88/qubtdocker:v1.1.1-caddy
        name: *name
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
      imagePullSecrets:
        - name: ghcr-secret