apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:/cc9TtzyiK7NWc4bhLVW62hif5ZXYUDBpJublv7/NqOX84WT1seyd29s6GyWZl4bxIvS2k2kFRo=,iv:Bgu2Ds8iW7ZdP9/USsPbpKrjXHmEFxf1My+pdhR93ko=,tag:dUn5jFnKQZpr/xrO9M9eRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqn46tdx7vazgkjuglseduk52plfrpz60zcqjqk83rfg8gwuv95qd4cem4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5THJTQ1Bhb0s5N3VOTkR4
            N2pnZlZDU256b1ZvWVZmNDN0TUZoUzBHYTI4Ck5pVTY5TmhEb24xVEFsVEEzMlA4
            U0FSYWt6TzdJUUNMeFBGZGhpUXlXdGcKLS0tIGpCd0l6NHhYc3hZd3VLVXZUSXVB
            KzlEajVRbmRsUnJXZzlHWUxVdnpHWGsKHVn4dG+QFSo840h/G+nob6w2UBWsV1mL
            ZGTW27b07+OWzvd17kDWfrnx0FhLElARZ971aZDiRNV2CbYC8Xq+tA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-02T13:32:03Z"
    mac: ENC[AES256_GCM,data:Nye+AVBd9gY2DmmqQMn33U4e42SMZSih7ZcjLLC68Idg9/d/Dq8UGWmNm2yW+yA+ttXtnxHwBjLYqTtRvwVaxlFaoFO51lxBP0JuBamv93Mqnsf/A2NoeNqaU/j4CyGPEbwJUGabAQ+HWcCemi3YqYQFVzxbp2bdYkwU5oyQL1M=,iv:6F3nIPO5C6te4L5vCHB4+XN0byfSfC7PxEYq+QdXpa4=,tag:DaNB3HJOK2sbyf+cFCnbOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
