---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 64.0.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    crds:
      enabled: true
    cleanPrometheusOperatorObjectNames: true
    # grafana
    grafana:
      enabled: false
    # alertmanager
    alertmanager:
      enabled: true
      alertmanagerSpec:
        retention: 24h
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: ceph-block
              resources:
                requests:
                  storage: 1Gi
    # prometheus
    prometheus:
      enabled: true
      prometheusSpec:
        replicas: 1
        scrapeInterval: 1m # <- match to Grafana helm chart ??
        retention: 2d
        retentionsize: 18Gi
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: ceph-block
              resources:
                requests:
                  storage: 20Gi
    # kubelet
    kubelet:
      enabled: true
    # kubeApiServer
    kubeApiServer:
      enabled: true
    # coreDNS
    coreDns:
      enabled: true
    # kubeControllerManager
    kubeControllerManager:
      enabled: true
      endpoints: &controlplane
        - 10.10.30.2
        - 10.10.30.3
        - 10.10.30.4
    # kubeEtcd
    kubeEtcd:
      enabled: true
      endpoints: *controlplane
    # kubeScheduler
    kubeScheduler:
      enabled: true
      endpoints: *controlplane
    # kubeProxy
    kubeProxy:
      enabled: false
    # kubeStateMatrics
    kubeStateMetrics:
      enabled: true
    kube-state-metrics:
      fullnameOverride: kube-state-metrics
    # nodeExpoter
    nodeExporter:
      enabled: true
    prometheus-node-exporter:
      fullnameOverride: node-exporter