---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/gateway.envoyproxy.io/clienttrafficpolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: envoy
  namespace: network
spec:
  proxyProtocol:
    optional: true # needed for towonel
  connection:
    bufferLimit: 64Mi # increase buffer from 32ki
  path:
    escapedSlashesAction: KeepUnchanged
  http2:
    onInvalidMessage: TerminateStream
  http3: {}
  tcpKeepalive: {}
  timeout:
    http:
      requestReceivedTimeout: 0s
  tls:
    minVersion: "1.2"
    alpnProtocols:
      - h2
      - http/1.1
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: Gateway