---
# yaml-language-server: $schema=https://k8s-schemas-cjso.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name external-dns-internal
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: external-dns
    namespace: flux-system
  install:
    disableSchemaValidation: true # Ref: https://github.com/kubernetes-sigs/external-dns/issues/5206
    remediation:
      retries: 3
  upgrade:
    disableSchemaValidation: true # Ref: https://github.com/kubernetes-sigs/external-dns/issues/5206
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *name
    logLevel: &logLevel debug
    serviceMonitor:
      enabled: true
    rbac:
      create: true
      additionalPermissions:
        - apiGroups: ['']
          resources: ['namespaces']
          verbs: ['get', 'watch', 'list']
        - apiGroups: ['gateway.networking.k8s.io']
          resources: ['gateways', 'httproutes']
          verbs: ['get', 'watch', 'list']
    sources:
      - gateway-httproute
    policy: sync
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/kashalls/external-dns-unifi-webhook
          tag: v0.7.0
        env:
          - name: UNIFI_HOST
            value: https://10.10.0.252
          - name: UNIFI_EXTERNAL_CONTROLLER
            value: 'false'
          - name: UNIFI_API_KEY
            valueFrom:
              secretKeyRef:
                name: external-dns-unifi-secret
                key: api-key
          - name: LOG_LEVEL
            value: *logLevel
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
    env:
      - name: EXTERNAL_DNS_GATEWAY_LABEL_FILTER
        value: gateway-label==internal-gateway
      - name: EXTERNAL_DNS_LABEL_FILTER
        value: route-label==external-dns-internal
