---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app forgejo
  namespace: flux-system
spec:
  targetNamespace: &namespace forgejo
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../flux/components/anubis
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: *namespace
  dependsOn:
    - name: cloudnative-pg-clusters
    - name: dragonfly-clusters
  path: ./cluster/kubernetes/apps/forgejo/forgejo/app
  prune: true
  postBuild:
    substitute:
      APP: *app
      ANUBIS_TARGET: http://forgejo-http.forgejo.svc.cluster.local:3000
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app forgejo-ingress
  namespace: flux-system
spec:
  targetNamespace: &namespace forgejo
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  healthChecks:
    - apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      name: forgejo
      namespace: *namespace
  healthCheckExprs:
    - apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      failed: status.parents[0].conditions.filter(e, e.type == 'Accepted').all(e, e.status == 'False')
      current: status.parents[0].conditions.filter(e, e.type == 'Accepted').all(e, e.status == 'True')
  path: ./cluster/kubernetes/apps/internal/forgejo/ingress
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
