---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name action-runner-controller-secret
  namespace: action-runner-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name # name of created secret
    template:
      data:
        ACTION_RUNNER_CONTROLLER_GITHUB_APP_ID: '{{ .ACTION_RUNNER_CONTROLLER_GITHUB_APP_ID }}'
        ACTION_RUNNER_CONTROLLER_GITHUB_INSTALLATION_ID: '{{ .ACTION_RUNNER_CONTROLLER_GITHUB_INSTALLATION_ID }}'
        ACTION_RUNNER_CONTROLLER_GITHUB_PRIVATE_KEY: '{{ .ACTION_RUNNER_CONTROLLER_GITHUB_PRIVATE_KEY }}'
  dataFrom:
    - extract:
        key: *name # 1p item name
