---
# yaml-language-server: $schema=https://k8s-schemas-cjso.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name k8s-runner
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: action-runner-controller
      namespace: action-runner-system
  valuesFrom:
    - targetPath: githubConfigSecret.github_app_id
      kind: Secret
      name: action-runner-controller-secret
      valuesKey: ACTION_RUNNER_CONTROLLER_GITHUB_APP_ID
    - targetPath: githubConfigSecret.github_app_installation_id
      kind: Secret
      name: action-runner-controller-secret
      valuesKey: ACTION_RUNNER_CONTROLLER_GITHUB_INSTALLATION_ID
    - targetPath: githubConfigSecret.github_app_private_key
      kind: Secret
      name: action-runner-controller-secret
      valuesKey: ACTION_RUNNER_CONTROLLER_GITHUB_PRIVATE_KEY
  values:
    githubConfigUrl: https://github.com/chrede88/home-ops
    minRunners: 1
    maxRunners: 3
    containerMode:
      type: kubernetes
      kubernetesModeWorkVolumeClaim:
        accessModes: ['ReadWriteOnce']
        storageClassName: ceph-block
        resources:
          requests:
            storage: 10Gi
    controllerServiceAccount:
      name: action-runner-controller
      namespace: action-runner-system
    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/home-operations/actions-runner:2.323.0@sha256:6d878ca00ecd301a5e5dab006d3ea96083e92f64e364a578f7b42bbc47ba738e
            command: ['/home/runner/run.sh']
            env:
              - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
                value: 'false'
        securityContext:
          fsGroup: 123
        serviceAccountName: *name
