---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.32.2/configmap-v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-configmap
  namespace: internal
  labels:
    app: homepage
data:
  kubernetes.yaml: |
    mode: disabled
  settings.yaml: |
    title: Cjso Homepage

    theme: dark
    color: slate

    useEqualHeights: true

    layout:
      Cluster:
        header: true
        style: row
        columns: 1
      Services:
        header: true
        style: row
        columns: 4
      Observability:
        header: false
        style: row
        columns: 3
      Misc:
        header: false
        style: row
        columns: 2
  services.yaml: |
    - Cluster:
        - Cluster:
            icon: talos.svg
            description: Prometheus
            widget:
              type: prometheusmetric
              url: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090
              refreshInterval: 10000 # in milliseconds
              metrics:
                - label: Cluster Age
                  query: round((time() - min(kube_node_created) ) / 86400)
                  format:
                    type: number
                    suffix: d
                - label: Available Nodes
                  query: count(count by (node) (kube_node_status_condition{condition="Ready"}))
                  format:
                    type: number
                - label: Running Pods
                  query: sum(kube_pod_status_phase{phase="Running"})
                  format:
                    type: number
                - label: Cluster CPU Usage
                  query: round(avg(instance:node_cpu_utilisation:rate5m) * 100, 0.1)
                  format:
                    type: number
                    suffix: '%'
                - label: Cluster Memory Usage
                  query: avg(instance:node_num_cpu:sum)
                  format:
                    type: number
                    suffix: '%'
    - Misc:
        - Unifi:
            icon: unifi.svg
            href: https://10.10.0.252/
            description: Unifi Network Application
            widget:
              type: unifi
              url: https://10.10.0.252
              username: "{{HOMEPAGE_VAR_UNIFI_NETWORK_USERNAME}}"
              password: "{{HOMEPAGE_VAR_UNIFI_NETWORK_PASSWORD}}"
        - Ceph:
            icon: ceph.svg
            href: https://ceph.local.cjsolsen.com
            description: Ceph Dashboard
    - Observability:
        - Grafana:
            icon: grafana.svg
            href: https://grafana.local.cjsolsen.com
            description: Grafana
            widget:
              type: grafana
              url: http://grafana.observability.svc.cluster.local:8080
              username: "{{HOMEPAGE_VAR_GRAFANA_USER}}"
              password: "{{HOMEPAGE_VAR_GRAFANA_PASSWD}}"
        - Gatus:
            icon: gatus.svg
            href: https://gatus.local.cjsolsen.com
            description: Gatus
            widget:
              type: gatus
              url: http://gatus.observability.svc.cluster.local:8080
        - Prometheus:
            icon: prometheus.svg
            href: https://prometheus.local.cjsolsen.com
            description: Prometheus
            widget:
              type: prometheus
              url: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090
    - Services:
        - GitHub:
            icon: github.svg
            href: https://github.com/chrede88
            description: My Github Repo
        - Website:
            icon: https://raw.githubusercontent.com/chrede88/home-ops/main/cluster/kubernetes/apps/internal/homepage/app/resources/cjso.svg
            href: https://cjsolsen.com
            description: Main Website
        - LinkTree:
            icon: https://raw.githubusercontent.com/chrede88/home-ops/main/cluster/kubernetes/apps/internal/homepage/app/resources/cjso.svg
            href: https://l1nkr.cjsolsen.com
            description: Linktree Website
        - Searxng:
            icon: https://raw.githubusercontent.com/chrede88/home-ops/main/cluster/kubernetes/apps/internal/homepage/app/resources/searxng.png
            href: https://search.local.cjsolsen.com
            description: Searxng
  widgets.yaml: |
    - logo:
        icon: https://raw.githubusercontent.com/chrede88/home-ops/main/cluster/kubernetes/apps/internal/homepage/app/resources/cjso.svg

    - openmeteo:
        label: Basel # optional
        latitude: 47.567869
        longitude: 7.595036
        timezone: Europe/Zurich
        units: metric
        cache: 5
        format:
          maximumFractionDigits: 1

    - search:
        provider: duckduckgo
        target: _blank

    - datetime:
        text_size: xl
        format:
          dateStyle: short
          timeStyle: short
          hour12: true
  bookmarks.yaml: ''
  docker.yaml: ''
  proxmox.yaml: ''
  custom.css: ''
  custom.js: ''
