---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name homepage
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      homepage:
        replicas: 1
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v1.1.1
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 3000
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  successThreshold: 1
                  failureThreshold: 5
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - 'ALL'
              runAsNonRoot: true
              runAsUser: 314
              runAsGroup: 314
              seccompProfile:
                type: RuntimeDefault
            resources:
              requests:
                memory: 128Mi
                cpu: 20m
              limits:
                memory: 512Mi
                cpu: 200m
            ports:
              - containerPort: *port
                name: http
            envFrom:
              - secretRef:
                  name: homepage-secret
    service:
      app:
        controller: *name
        ports:
          http:
            port: 8080
    persistence:
      config:
        type: emptyDir
        globalMounts:
          - path: /app/config/logs
      config-file:
        type: configMap
        name: hompage-configmap
        globalMounts:
          - path: /app/config/custom.js
            subPath: custom.js
            readOnly: true
          - path: /app/config/custom.css
            subPath: custom.css
            readOnly: true
          - path: /app/config/bookmarks.yaml
            subPath: bookmarks.yaml
            readOnly: true
          - path: /app/config/docker.yaml
            subPath: docker.yaml
            readOnly: true
          - path: /app/config/kubernetes.yaml
            subPath: kubernetes.yaml
            readOnly: true
          - path: /app/config/services.yaml
            subPath: services.yaml
            readOnly: true
          - path: /app/config/settings.yaml
            subPath: settings.yaml
            readOnly: true
          - path: /app/config/widgets.yaml
            subPath: widgets.yaml
            readOnly: true
