---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name homepage-secret
  namespace: internal
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name # name of created secret
    template:
      data:
        HOMEPAGE_VAR_UNIFI_NETWORK_USERNAME: '{{ .HOMEPAGE_VAR_UNIFI_NETWORK_USERNAME }}'
        HOMEPAGE_VAR_UNIFI_NETWORK_PASSWORD: '{{ .HOMEPAGE_VAR_UNIFI_NETWORK_PASSWORD }}'
        HOMEPAGE_VAR_PIHOLE0_API_KEY: '{{ .HOMEPAGE_VAR_PIHOLE0_API_KEY }}'
        HOMEPAGE_VAR_PIHOLE1_API_KEY: '{{ .HOMEPAGE_VAR_PIHOLE1_API_KEY }}'
        HOMEPAGE_VAR_PIHOLE2_API_KEY: '{{ .HOMEPAGE_VAR_PIHOLE2_API_KEY }}'
        HOMEPAGE_VAR_PIHOLE3_API_KEY: '{{ .HOMEPAGE_VAR_PIHOLE3_API_KEY }}'
        HOMEPAGE_VAR_GRAFANA_USER: '{{ .HOMEPAGE_VAR_GRAFANA_USER }}'
        HOMEPAGE_VAR_GRAFANA_PASSWD: '{{ .HOMEPAGE_VAR_GRAFANA_PASSWD }}'
  dataFrom:
    - extract:
        key: *name # 1p item name
