---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.32.2/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: homepage-web-svc
  namespace: internal
spec:
  selector:
    app: homepage
  ports:
    - name: http
      targetPort: 3000
      port: 80
