---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-internal
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.14.4
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: external-dns-internal
    serviceMonitor:
      enabled: true
    rbac:
      create: true
      additionalPermissions:
        - apiGroups: [""]
          resources: ["namespaces"]
          verbs: ["get","watch","list"]
        - apiGroups: ["gateway.networking.k8s.io"]
          resources: ["gateways","httproutes","grpcroutes","tlsroutes"]
          verbs: ["get","watch","list"]
    sources:
      - gateway-httproute
      - gateway-grpcroute
      - gateway-tlsroute
    policy: upsert-only
    registry: noop
    provider: pihole
    env:
      - name: EXTERNAL_DNS_PIHOLE_SERVER
        value: http://pihole-0.pihole.network.svc.cluster.local
      - name: EXTERNAL_DNS_GATEWAY_LABEL_FILTER
        value: gateway-label==internal-gateway
      - name: EXTERNAL_DNS_LABEL_FILTER
        value: route-label==external-dns-internal
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: pihole-secret
            key: EXTERNAL_DNS_PIHOLE_PASSWORD