---
# yaml-language-server: $schema=https://crd.movishell.pl/gateway.envoyproxy.io/clienttrafficpolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: envoy
spec:
  clientIPDetection:
    xForwardedFor:
      numTrustedHops: 1
  path:
    disableMergeSlashes: true
    escapedSlashesAction: KeepUnchanged
  connection:
    bufferLimit: 64Mi
    maxAcceptPerSocketEvent: 0
  headers:
    lateResponseHeaders:
      add:
        - name: Strict-Transport-Security
          value: "max-age=31536000; includeSubDomains; preload"
      remove:
        - x-powered-by
        - server
        - via
        - DP-SSO-Domain

  http2:
    initialStreamWindowSize: 2Mi
    initialConnectionWindowSize: 32Mi
    onInvalidMessage: TerminateStream
  http3: {}
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: internal-gateway
  tcpKeepalive: {}
  timeout:
    http:
      requestReceivedTimeout: 0s
  tls:
    minVersion: "1.2"
    alpnProtocols:
      - h2
      - http/1.1