---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.32.2/configmap-v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-ddns-configmap
  namespace: network
data:
  TZ: 'Europe/Zurich'
  DOMAINS: cjsolsen.com
  PROXIED: 'true'
  IP6_PROVIDER: 'none'
  DELETE_ON_STOP: 'false'
  UPDATE_CRON: '@every 10m'
  QUIET: 'false'
