---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.32.2/deployment-apps-v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name cloudflare-ddns
  namespace: network
  labels:
    app: *name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *name
  template:
    metadata:
      labels:
        app: *name
    spec:
      containers:
        - image: favonia/cloudflare-ddns:1.15.1
          name: *name
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: cloudflare-ddns-configmap
            - secretRef:
                name: cloudflare-ddns-secret
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ['ALL']
            seccompProfile:
              type: RuntimeDefault
            runAsNonRoot: true
            runAsUser: 314
            runAsGroup: 314
