---
# yaml-language-server: $schema=https://k8s-schemas-cjso.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: l1nkr
  namespace: external
spec:
  parentRefs:
    - name: external-gateway
      namespace: network
      sectionName: l1nkr
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: l1nkr-web-svc
          port: 8080
