---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/gateway.envoyproxy.io/clienttrafficpolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: envoy
  namespace: network
spec:
  targetRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: external-gateway
  proxyProtocol:
    optional: true