---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: towonel-agent
  namespace: network
spec:
  interval: 30m
  timeout: 15m
  chartRef:
    kind: OCIRepository
    name: towonel-agent
    namespace: flux-system
  values:
    replicaCount: 2
    serviceAccount:
      create: true
    agent:
      logLevel: info
      inviteTokenSecret:
          name: towonel-agent-secret
          # -- Key inside the Secret.
          key: agent-invite-token
    monitoring:
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
      dashboards:
        enabled: false

