---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - namespace.yaml
  - pod-monitor.yaml
  # new flux operator
  - ./flux/ks.yaml
# components:
#   - ../../flux/components/alerts
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: not-used
      namespace: flux-system
    unsetOnly: true
