---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  # Pre Flux-Kustomizations
  - namespace.yaml
  - pod-monitor.yaml
  # new flux operator
  - ./flux/ks.yaml
components:
  - ../../flux/components/alerts
