---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./pihole/ks.yaml
  - ./orbitalsync/ks.yaml
  - ./gateways/ks.yaml
  - ./cloudflare-ddns/ks.yaml
  - ./external-dns/ks.yaml
components:
  - ../../flux/components/alerts
