---
# yaml-language-server: $schema=https://k8s-schemas-cjso.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app internal-ingress
  namespace: flux-system
spec:
  targetNamespace: &namespace network
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  healthChecks:
    - apiVersion: gateway.networking.k8s.io/v1
      kind: Gateway
      name: internal-gateway
      namespace: *namespace
    - apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      name: http-https-redirect
      namespace: *namespace
  healthCheckExprs:
    - apiVersion: gateway.networking.k8s.io/v1
      kind: Gateway
      failed: status.conditions.filter(e, e.type == 'Accepted').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Accepted').all(e, e.status == 'True')
    - apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      failed: status.parents.conditions.filter(e, e.type == 'Accepted').all(e, e.status == 'False')
      current: status.parents.conditions.filter(e, e.type == 'Accepted').all(e, e.status == 'True')
  dependsOn:
    - name: cilium
  path: ./cluster/kubernetes/apps/network/gateways/internal
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://k8s-schemas-cjso.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app external-ingress
  namespace: flux-system
spec:
  targetNamespace: &namespace network
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  healthChecks:
    - apiVersion: gateway.networking.k8s.io/v1
      kind: Gateway
      name: external-gateway
      namespace: *namespace
    - apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      name: http-https-redirect-external
      namespace: *namespace
  healthCheckExprs:
    - apiVersion: gateway.networking.k8s.io/v1
      kind: Gateway
      failed: status.conditions.filter(e, e.type == 'Accepted').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Accepted').all(e, e.status == 'True')
    - apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      failed: status.parents.conditions.filter(e, e.type == 'Accepted').all(e, e.status == 'False')
      current: status.parents.conditions.filter(e, e.type == 'Accepted').all(e, e.status == 'True')
  dependsOn:
    - name: cilium
  path: ./cluster/kubernetes/apps/network/gateways/external
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
