apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-ddns-configmap
  namespace: network
data:
  TZ: "Europe/Zurich"
  DOMAINS: cjsolsen.com
  PROXIED: "true"
  IP6_PROVIDER: "none"
  DELETE_ON_STOP: "false"
  UPDATE_CRON: "@every 10m"
