apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
  namespace: network
  labels:
    app: cloudflare-ddns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-ddns
  template:
    metadata:
      labels:
        app: cloudflare-ddns
    spec:
      containers:
      - image: favonia/cloudflare-ddns:1.15.0
        name: cloudflare-ddns
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: cloudflare-ddns-configmap
          - secretRef:
              name: cloudflare-ddns-secret
        securityContext:
          runAsUser: 314
          runAsGroup: 314
