apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: network
type: Opaque
data:
    CF_API_TOKEN: ENC[AES256_GCM,data:K6fFqH0dDUYf3ChTYu8oZp7mmEioiBnD3nkzFEXd7sycOdvTIUrK8iLowjZFdrED8Ff32E/ffBk=,iv:m6Nyf/LP3XFL0CfHoBLQ8or+K+1uzWX+1j7hEXgRsuI=,tag:HKDo6b1UUCFl0MTbjTZZyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqn46tdx7vazgkjuglseduk52plfrpz60zcqjqk83rfg8gwuv95qd4cem4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdENRV1lkRnh0U2I3SmtT
            L29DRFNHYzlsV2dKUVVPaytEaVpFNlJ6K2hjClozdUhBR3BiSTZ0Y2NPaEJWczRU
            bm5na3FLTDBDZUcwTUVSUDlaYzZtaFUKLS0tIFZia042NlIxMDJWcE1zRk1QOHc1
            RmJnU0JaRmQza2hMVGxDaWppNGpHVDQK96WvPF3XiozkaLFYww8AsqhzBJCVZTpI
            l4DunCNtyT41M5KVkomQfn+f+EJGlxdmFOekZ9LTXu9w959RU5ukdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-10T11:27:04Z"
    mac: ENC[AES256_GCM,data:iL/q2/75p7cfAZsUMO7QqgDztDOTNzF1/k1p8j6EP6grS/+46kGk9yntTFLlqYO1MQcMooGwiriSBpLeS9oKsxGzR7b3jcWhWtdoAbD23gSbhVd2xh6ZciUmpe+vL3XZd30+/VrjHjFtEub6zmLA/sgf6GUHjbdT8GuLQeE5xms=,iv:8IC/PKZzeK4SkOT0aEneN85gz6Orw1Z5sDYbjsgzC/M=,tag:bR1JwpIh9cuVp0DJUQqLgg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
