apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gatus-service-monitor
  namespace: internal
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: http
  selector:
    matchLabels:
      name: gatus-web-svc