---
apiVersion: v1
kind: Service
metadata:
  name: gatus-web-svc
  namespace: internal
  labels:
    app: gatus
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: gatus