---
# yaml-language-server: $schema=https://k8s-schemas-cjso.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app l1nkr
  namespace: flux-system
spec:
  targetNamespace: &namespace external
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: *namespace
  path: ./cluster/kubernetes/apps/external/l1nkr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://k8s-schemas-cjso.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app l1nkr-ingress
  namespace: flux-system
spec:
  targetNamespace: &namespace external
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  healthChecks:
    - apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      name: *app
      namespace: *namespace
  healthCheckExprs:
    - apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      failed: status.parents[0].conditions.filter(e, e.type == 'Accepted').all(e, e.status == 'False')
      current: status.parents[0].conditions.filter(e, e.type == 'Accepted').all(e, e.status == 'True')
  path: ./cluster/kubernetes/apps/external/l1nkr/ingress
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
