---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app l1nkr
  namespace: flux-system
spec:
  targetNamespace: external
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./cluster/kubernetes/apps/external/l1nkr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app l1nkr-ingress
  namespace: flux-system
spec:
  targetNamespace: external
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./cluster/kubernetes/apps/external/l1nkr/ingress
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
