---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.32.2/deployment-apps-v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name gatus
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *name
  template:
    metadata:
      name: *name
      namespace: observability
      labels:
        app: *name
    spec:
      serviceAccountName: *name
      terminationGracePeriodSeconds: 5
      containers:
        - image: twinproduction/gatus:v5.17.0
          imagePullPolicy: IfNotPresent
          name: *name
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          # securityContext:
          #   allowPrivilegeEscalation: false
          #   capabilities:
          #     drop: ["ALL"]
          #   seccompProfile:
          #     type: RuntimeDefault
          #   runAsNonRoot: true
          #   runAsUser: 314
          #   runAsGroup: 314
          envFrom:
            - secretRef:
                name: gatus-secret
          resources:
            limits:
              cpu: 250m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          volumeMounts:
            - mountPath: /config
              name: gatus-config
      volumes:
        - configMap:
            name: gatus
          name: gatus-config
    # securityContext:
    #     sysctls:
    #       - name: net.ipv4.ping_group_range
    #         value: 0 65536
