---
# yaml-language-server: $schema=https://k8s-schemas-cjso.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name gatus-secret
  namespace: observability
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name # name of created secret
    template:
      data:
        GATUS_USER: '{{ .GATUS_USER }}'
        GATUS_PASSWD: '{{ .GATUS_PASSWD }}'
        PUSHOVER_TOKEN: '{{ .PUSHOVER_TOKEN }}'
        PUSHOVER_USER_KEY: '{{ .PUSHOVER_USER_KEY }}'
  dataFrom:
    - extract:
        key: *name # 1p item name
