---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name gatus
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      gatus:
        replicas: 1
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: twinproduction/gatus
              tag: v5.22.0
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8080
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  successThreshold: 1
                  failureThreshold: 5
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: true
              # capabilities:
              #   drop:
              #     - 'ALL'
              #   add:
              #     - 'NET_RAW'
            resources:
              limits:
                cpu: 250m
                memory: 100Mi
              requests:
                cpu: 50m
                memory: 50Mi
            ports:
              - containerPort: *port
                name: http
                protocol: TCP
            envFrom:
              - secretRef:
                  name: gatus-secret
        serviceAccount:
          identifier: gatus
    # defaultPodOptions:
    #   securityContext:
    #     runAsNonRoot: true
    #     runAsUser: 1000
    #     runAsGroup: 1000
    #     fsGroup: 1000
    #     fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: *name
        ports:
          http:
            port: *port
    serviceMonitor:
      app:
        serviceName: *name
        endpoints:
          - port: http
    serviceAccount:
      gatus: {}
    persistence:
      config:
        type: emptyDir
      config-file:
        type: configMap
        name: gatus-configmap
        globalMounts:
          - path: /config/config.yaml
            subPath: config.yaml
            readOnly: true
