---
# yaml-language-server: $schema=https://k8s-schemas-cjso.pages.dev/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gatus-service-monitor
  namespace: observability
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: http
  selector:
    matchLabels:
      app: gatus
