---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.32.2/serviceaccount-v1.json
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gatus
  namespace: observability
