---
apiVersion: v1
kind: Service
metadata:
  name: gatus-web-svc
  namespace: observability
  labels:
    app: &name gatus
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: *name
