apiVersion: v1
kind: Secret
metadata:
  name: connect-server-credentials
  namespace: external-secrets
type: Opaque
stringData:
  #ENC[AES256_GCM,data:vopZ9jFZjW3gU+jGjMJwuB12x+2cv8KX/QIG21sLlrCZ1s++kED+EUbIBC2ftFUd1evv6iLzwj7Fo76+dR7LTck1goxx6wrUZFA1+PQun5ElSEyjUZyrjVNhhELik+jPS2O5Jiw9kgccF0opBlPPdyGm0IQ83ini+Bsi0WPlELbGQQNWk1CT8jazoVzKVbimmYonz8iiLP4DanvAycF9B/uSIVoYtg/I84UPjCTADiaKUZmZzxlQuxVd7g==,iv:nyVkAfoC0CpSVG52i/KQzuH0YsqUyNdkvfuVvIm25m0=,tag:hvE4+p/cDTqhStXWA6NzDg==,type:comment]
  1password-credentials.json: ENC[AES256_GCM,data:XxqG1cVWyGoXi2zhjWZjPBjYhfTIi0wwaJf3oFeaioqbnPXSxUCf3iN//VFmIev2IbEcfmiloim+p0nXuOU4oUDm6PgFuA5xoFFtXF7z2pyXj5Q0gNE++GTXfbx3q20fSzbohE/hmbiEk9ODlnZqMVOUX86QMnj3Azgjbewjg1NbHYTM+uOGCweQMSN/domVROXXnYTCL6biUlnK0rINwL/F73W4pTQdz0KVnMWXhRIdyyVtKmCdmCMM2qf6mr2TFafHBOzrzhSMlHR5uoExsPmqRVu/euYD14FGhOmqQYbO+x/BfIffph01gskck23Il9Wc7dLIFzbW2P8LLxAQbJXvXcCLTclJCKVA+0EUfx+0gwtiju8CZHX8stjYXjSX1BKdqj2XFWLgdycICyC4OemFsQcQTMkJwh+x3JDRUDgGJiySG4BG4FfVyrMqvFoHCdKxRypwX2Fi4vMRFY7mIe5dEb6wF3kJ+liAvBhpQe2vuYGGmQ97zT0ADp8fROQsQ9OjGv1mQvvg+D61qE3QKatyDXhE77VcpU+SKnCcZVXyhM5j153z9xpMPRf2WPRMFte9Uxc1GC/mo4DpySTgGox2iRXrvde45M1/62wSVoX7GQin2T7HdVU2Bt0tw/nQ77jxA63f8cjOJMQn1GdTgmKmUqrzuqsOHCCUKeSsQCCJusZjRM79kaIzwxPoU4CTHk7nyjrH7Uf0FtrxdDKekYfcAjQFnfCVNeFrFE1FTjRya4e0aGpSdtn907FhH5wFwhwhRBb5CngIXs48ZykuLhQfiHISP83NhCgj0gch5SFAx+UQ2U69uPWpgWX9lI2TgX6HnsL2XyHlsU1saBuj350teuXlkSluGr23/1vL3zu+i84TEwx5o1v832GxUCvK6SXQwGjLgfn535daifNdZ9p4ZpcYGQgdTZkRYDV+/iGUxu1C4FYObrzRiOz5vQO8Yh14BzkmfizPqra1wMavUfSBIpxuhbOx2fCYTYgQAl7wk6wdBQgeUJLsc4kHD7q8FiRi/uAQEgRus4RhDrYNomy0xDBTb4L9fSNcajmjN98I4V3tt6IJeWxRHNDEVFaNgbwrYjVH9z/9vTnkDwHRJs7DATaHopCHZFvkOxAfcEVCsG0TaJrH0Vj09XlU/JrAZ2knUqKFCJDjSgX9KvRzLL+Eb9ljBMBkHdk6E5XDqm0Ah6p27l/W7gZIqRPJTzSVH4mXUQhnQ/aKcPkoIPagLiIpvHmD9Yi+zfZ097YzEONFcHk1RTAKm/jDTBNm2HIol1mB6YIkwrS1rCAIuWDH6lOx3PJnbIFBjG5x+xz+Gsz1LylDRylZ09Y1tXv7yGP6PjY7unVTtVO7rvsv/F1ZsROrtO0txC0ZwwB2r6YgO8qbgWq2/CUDiEBi3F5yW4g792Kw5AVzj9o6TPKkUQ4JUzlv77RCY3/C10HHE5BUAtkvw6FyxSgSKEq3Oh0P1mer5PlpN5PVGkneM0zUgEfxhpBI5gbYmsEurGwPvMABuzxLk6WMLvjnEagbQstEwS9lY4ffVlSPzKnVL/jtVKnrGwSZkGidwvy3MBYORamRa6183Rvp2MTblZnKd71qRhor6CPwLDIIuzX+euAmNOOFnGULcdjgIkZbM4RDFWd1kpUkIBC23B5p35QMJbub2PjSwkSQqHwoF/R3h6v6QokOIfb5jjKZHiCdrQEsalA369QoAz3N1pAg/tz10E+YjqMT8H+UZhGpzqCUE+jyYFoqvSOjAnQdVpbPHEalR2tVIj/L2iJM7RGAgx+2fIfX7TMv0j8wQfZMxOmoxubryb+3u0devC0=,iv:1RRU8PUbQib1qT3Wqmrgsiiwno2+a/H+XLEYiBgDMnI=,tag:QBvwuZ/7yPIXIyj37S6ojA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nqn46tdx7vazgkjuglseduk52plfrpz60zcqjqk83rfg8gwuv95qd4cem4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQlBZa0lUUjArR2EzMXM3
        TjMxSnMxT0pwYXBWVWZkZ1pvcWphTjFhTkIwCkM3ZlNGOFZxS3dwRUFoMVNhSHJa
        SFk0dkkzdzg0WnFzTEJWMDBOQ2Z6SzQKLS0tIG9qSURDYW1HK214NXpRWWl3N1Fa
        NWwvWmgwUjVQZTdSVEVWL21xZWRFOE0KrwwwOg3EPepK2Mn7LiBo1ZHqzwh6fOGJ
        M9LoBWxYwJ4sThRgmWsmUMdYNDXTC9kmCN3xysxzBn9Qq3H+C1DXHw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-01T21:02:00Z"
  mac: ENC[AES256_GCM,data:rGm6P7h1sGmt8UvQPYe0KozBUXi4DLbycixcJF4gcCbvseAuS9pcWPlwD9zhR3KpuPFby/Yl9uRaWZ5O74zLYFMuMiRsbtTu3zowRpcisSn76cfEU4yo2kFTdMKj28+sLUw3rRtsNsnRYhc8YX58566dY6ETVPnzrzbJLB2w3a0=,iv:McX1fQx7IwkvKjvnECR2fW1lZbuuSOcV5396OjY1A94=,tag:GTF5f8cvFkWhDA6lzdt6PQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
