apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - slack-token.yaml
  - notifications.yaml
  - pod-monitor.yaml

  # new flux operator
  - ./flux/ks.yaml
