apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Pre Flux-Kustomizations
- gotk-components.yaml
- gotk-sync.yaml
- slack-token.yaml
- notifications.yaml
# - pod-monitor.yaml
