apiVersion: apps/v1
kind: Deployment
metadata:
  name: qubt
  namespace: external
  labels:
    app: qubt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qubt
  template:
    metadata:
      labels:
        app: qubt
    spec:
      containers:
      - image: ghcr.io/chrede88/qubtdocker:v2.0.0
        name: qubt
        ports:
          - name: web
            containerPort: 8080
          - name: metrics
            containerPort: 2019
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
      imagePullSecrets:
        - name: ghcr-secret