apiVersion: v1
kind: Secret
metadata:
    name: ghcr-secret
    namespace: external
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:MEbldlL3pSWiRVZc/2+NQ/q/KXhyx5mkiYSCw1kUrKsy7fkl7dmC0EyjttsjE/YXBw5LhmcdBMqHNwZzNogPGkxNeNc0JQQtMlDVe6E0wfoG460cScG+QHYiqQoo+tQiqX1iEzMgRR+KoWkacFl49Bw4ZD1FMZ9+tsn6wM7yvLpFdn/epTr/Hg==,iv:/4jK86TiPRHAooNCHuoU5nMdKj417D+V20448jBOX7k=,tag:lcf4Bpxa93wyLXPwzHQMYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqn46tdx7vazgkjuglseduk52plfrpz60zcqjqk83rfg8gwuv95qd4cem4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtS05FRFlKS3VlMit2OTNh
            U3I1MXBicDU4K05zZC8yck9jcFR2NFluRXhVCkZzeVNCSUkySWVoVTYyV2p0SUNQ
            aDBMZUR5a2Y0Tmxsd2ZscTM1aWlhMkUKLS0tIG9CeC9vSCs1eHYzQXlkU0JqU3Zp
            MUxWYkFCTHluVmFTSVNPUTlwKytCbTgKbKsG8fymWGSCvHKoHuSKFYBZA6WYYC0S
            pJvL0EgwQd4m0BaCy+vmFu34wHB7rpCo0AmasrCXC/1ZFq5uTQGm1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-03T20:09:30Z"
    mac: ENC[AES256_GCM,data:gjDhBFQ8nmPRGUzos9dDIYauUCgY3jfT+oceS0yJtezgq7PNsX5oMCawKENTqbLtM+7VvONAQrhGwIToSHoqAvPndcEpwW61kh82W5Zbag3tmQbcuU2g86CQpX5vU+YrF1H045DaWmDSzbB2+LNAJGYAlotAYv5AbER42U7cIvM=,iv:ZrfA8Opd5BF3a+HJAfRpA5lhfWkp+OdLaBLoTLRJK+k=,tag:jltr13SPDh1eWpR+KzvCYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
