---
kind: Service
apiVersion: v1
metadata:
  name: pihole-dns-udp-svc
  namespace: network
  annotations:
    "io.cilium/lb-ipam-ips": "10.10.30.70"
    # "io.cilium/lb-ipam-sharing-key": "pihole-dns-key"
spec:
  selector:
    app: pihole
  type: LoadBalancer
  loadBalancerClass: io.cilium/l2-announcer
  ports:
    - name: svc-53-udp-dns
      port: 53
      targetPort: 53
      protocol: UDP
    - name: svc-53-tcp-dns
      port: 53
      targetPort: 53
      protocol: TCP
# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: pihole-dns-tcp-svc
#   namespace: network
#   annotations:
#     "io.cilium/lb-ipam-sharing-key": "pihole-dns-key"
# spec:
#   selector:
#     app: pihole
#   type: LoadBalancer
#   loadBalancerClass: io.cilium/l2-announcer
#   ports:
#     - name: svc-53-tcp-dns
#       port: 53
#       targetPort: 53
#       protocol: TCP