---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  - ./notifications.yaml
  # Flux-Kustomizations
  - ./qubt/ks.yaml
  - ./l1nkr/ks.yaml
  - ./kromgo/ks.yaml
