apiVersion: v1
type: kubernetes.io/basic-auth
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: database
    labels:
        cnpg.io/reload: "true"
data:
    username: ENC[AES256_GCM,data:p9k0pcLigK/CfZYU,iv:15kVtV1ulnhkt9EPXiNVis6oQhymPuXMTQutTUhUAi8=,tag:a3wPWL6JTy24OxIpOf8Qvw==,type:str]
    password: ENC[AES256_GCM,data:7FJEfbN+rINox52WXcxzBnN92wfGEEDTrg4NUJTzFQ6wbrKzLx7iTg==,iv:zwpLZ1vMWILAAAtQVkWsPmNjZ8W1osU+9zloaE8SsEM=,tag:E7jrstO9rGPNsyAi8BxXAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqn46tdx7vazgkjuglseduk52plfrpz60zcqjqk83rfg8gwuv95qd4cem4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDeW81RjZHOTVVaE00OC9H
            aUIrd3RhckNkbnVYUHMwdW85cElrWXgwdURFCkw4Yk9UMmhEcU5ZdXNKOUF3eDBs
            Y2tleFRGTHk3MTU5SzhxbkVNODVjRGcKLS0tIHg1b2llMkdwenZSalZXcDFYdGxM
            MjI4cmJYZFFwbDhVMXJMSkFHZDQ0YmMKElTJPXVnHYUdiw6SF18G5HBSm010BBVZ
            J6a4+WdRWHezyaX65ZIcZZJPOxiwizLKmssUfwrQ4e/lUQf/kNoLxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-17T10:58:32Z"
    mac: ENC[AES256_GCM,data:HbXhXDTsE4XY1497ZpefNmnbhgw8lR2lzdLcnu4r4l1acfaAqgPlSJfmdRO+hc4Xn38c5QFXipSV1lVucEsyD7zZVSAMN7wK5Jj3/ey/Yhc1cV8HFZcjWPNuD0OBDDzcA8KSRxEds8iaCDLqORIMKlIGMkL1dX8dSTlh1l0mwvE=,iv:lvT3Jwokty0P9vufg1cx0mfK8A9XEls63G4uI0WClrc=,tag:0d6gAqk8O7rCGRtCUZ7tgw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
