apiVersion: v1
type: kubernetes.io/basic-auth
kind: Secret
metadata:
    name: gatus-user-secret
    namespace: database
    labels:
        cnpg.io/reload: "true"
data:
    username: ENC[AES256_GCM,data:OdVPIqZYfSk=,iv:aFZK83sZyFIA/61E+vO24k8ukpFRiiUrFyZ6I1RELA8=,tag:15T3kRcrNRmMwK/Uzm9ZAA==,type:str]
    password: ENC[AES256_GCM,data:YVLfSJLKZn4Yz5VYDCU0jt1GNSSdhePPjWPslXwfdX7cndk+mujYRg==,iv:Zbs167iUQ8N4tYiduKinwy8x18dAdSH8JofLq0tXA4k=,tag:WiHfjNSnVwpByD/VZrrhEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqn46tdx7vazgkjuglseduk52plfrpz60zcqjqk83rfg8gwuv95qd4cem4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxb2g4cytKQ2ZCcTZXSFFP
            cTBwWFNuMzFsZjFsQlk5SFpQemFqNVkvRDFrCllUNWFmcnBReHZMdTVKa0V1N0M4
            S29wcTJJRUIvTHBBRDdmc2VBS1Z0UEEKLS0tIGZkMkpjc2pESU8yODRZWENEWFZS
            clhCVENhQTRUdVZKZURwQk9aTlYzaEUKXcNlHPugDpuPC/Nt9FeZ/Z3YpLE0JU2B
            0yKuLw3QfRjhWF9Bi00wbuehe/B2LOrvWaZBI9OaqTZTC/S2Qk063Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-17T11:03:01Z"
    mac: ENC[AES256_GCM,data:MOtpn7SV72oFM4PimxOPSC/2AD0qWWF6OoxvD/BlpMlvaiGauXvhXulhsUpkSGa3/W4IqSIAPd3DVPBa6l98/ZeE0qeKzvBXvuE/uixtahH8iYVs5SECfTksDe7gWLDW/1Y7SLT+AGsbo8lfFak9x2A3LrltvviJlwYCZWJeBJc=,iv:MIiUU108UVI8UG7aOnf0ey7kEBGJcxXOi+y0JgNwSsc=,tag:n+6CoRrrxiPY/TjWpV4h3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
