---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gatus-cluster
  namespace: database
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6-10
  bootstrap:
    initdb:
      database: gatus
      owner: gatus
      secret:
        name: gatus-user-secret
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true
  superuserSecret:
    name: cloudnative-pg-secret
  resources:
    requests:
      cpu: 100m
      memory: 500Mi
    limits:
      cpu: 500m
      memory: 1Gi
  postgresql:
    parameters:
      shared_buffers: 128MB
      timezone: "Europe/Zurich"
  storage:
    size: 5Gi
    storageClass: ceph-block
  monitoring:
    enablePodMonitor: true