---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  - ./slack-token.yaml
  - ./notifications.yaml
  # Flux-Kustomizations
  # - ./pihole/ks.yaml
  # - ./orbitalsync/ks.yaml
  # - ./gateways/ks.yaml
  # - ./cloudflare-ddns/ks.yaml
  # - ./external-dns/ks.yaml