---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kromgo
  namespace: flux-system
spec:
  targetNamespace: external
  commonMetadata:
    labels:
      app.kubernetes.io/name: kromgo
  dependsOn:
    - name: kube-prometheus-stack
  path: ./cluster/kubernetes/external/kromgo/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 15m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kromgo-ingress
  namespace: flux-system
spec:
  targetNamespace: external
  commonMetadata:
    labels:
      app.kubernetes.io/name: kromgo-ingress
  dependsOn:
    - name: kromgo
  path: ./cluster/kubernetes/external/kromgo/ingress
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 15m
