---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./kube-prometheus-stack/ks.yaml
  - ./grafana/ks.yaml
  - ./unpoller/ks.yaml
  - ./gatus/ks.yaml
components:
  - ../../flux/components/alerts
