---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./kube-prometheus-stack/ks.yaml
  - ./grafana/ks.yaml
  - ./unpoller/ks.yaml
  - ./gatus/ks.yaml
components:
  - ../../flux/components/alerts
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: not-used
      namespace: cert-manager
    unsetOnly: true
