# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: archiveteam
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      archiveteam:
        replicas: 1
        containers:
          app:
            image:
              repository: atdr.meo.ws/archiveteam/warrior-dockerfile
              tag: latest
            resources:
              requests:
                cpu: 20m
                memory: 128Mi
              limits:
                cpu: 100m
                memory: 256Mi
            env:
              DOWNLOADER: chrede88
              SELECTED_PROJECT: auto
              CONCURRENT_ITEMS: 6
              SHARED_RSYNC_THREADS: 2
            securityContext:
              runAsNonRoot: true
              runAsUser: 314
              runAsGroup: 314
              fsGroup: 314
              fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /projects
