---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cluster.yaml
  - ./renovate-cluster.yaml
  - ./podmonitor.yaml
  - ./renovate-cluster-podmonitor.yaml
