---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: 'Flux Diff'

on:
  pull_request:
    branches: ['main']
    paths: ['cluster/kubernetes/**']

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: write

jobs:
  flux-diff:
    name: Flux Diff
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        resource:
          - helmrelease
          - kustomization
    steps:
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@v2.5.1
      - name: Run diff
        uses: allenporter/flux-local/action/diff@7.0.0
        id: diff
        with:
          live-branch: main
          path: cluster/kubernetes/flux/main
          resource: ${{ matrix.resource }}
          debug: true
      - name: PR Comments
        uses: mshick/add-pr-comment@v2
        if: ${{ steps.diff.outputs.diff != '' }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message-id: ${{ github.event.pull_request.number }}/${{ matrix.resource }}
          message-failure: Unable to post kustomization diff
          message: |
            ```diff
            ${{ steps.diff.outputs.diff }}
            ```
