---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Flux Local

on:
  pull_request:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  filter:
    name: Flux Local - Filter
    runs-on: ubuntu-slim
    timeout-minutes: 5
    outputs:
      changed-files: ${{ steps.changed-files.outputs.changed_files }}
    steps:
      - name: Get Changed Files
        id: changed-files
        uses: bjw-s-labs/action-changed-files@a9a36fb08ce06db9b02fbd8026cc2c0945eb9841 # v0.6.0
        with:
          patterns: cluster/kubernetes/**/*

  test:
    if: ${{ needs.filter.outputs.changed-files != '[]' }}
    needs: filter
    name: Flux Local - Test
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - name: Checkout files
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@1fd61a06264d71cf445ed55c4f14d401d26a1c64 # v2.8.8

      - uses: allenporter/flux-local/action/test@4d666add25002f550dc0dbe8b2b2f25859169b34 # 8.2.0
        with:
          path: cluster/kubernetes/flux/main
          enable-helm: true
          debug: true

  diff:
    if: ${{ needs.filter.outputs.changed-files != '[]' }}
    needs: filter
    name: Flux Local - Diff
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    permissions:
      contents: read
      pull-requests: write
    strategy:
      matrix:
        resource:
          - helmrelease
          - kustomization
    steps:
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@1fd61a06264d71cf445ed55c4f14d401d26a1c64 # v2.8.8

      - name: Run diff
        uses: allenporter/flux-local/action/diff@4d666add25002f550dc0dbe8b2b2f25859169b34 # 8.2.0
        id: diff
        with:
          live-branch: main
          path: cluster/kubernetes/flux/main
          resource: ${{ matrix.resource }}
          debug: false

      - name: PR Comments
        uses: mshick/add-pr-comment@8e4927817251f1ff60c001f04568532b38e0b4a0 # v3.11
        if: ${{ steps.diff.outputs.diff != '' }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message-id: ${{ github.event.pull_request.number }}/${{ matrix.resource }}
          message-failure: Unable to post kustomization diff
          message: |
            ```diff
            ${{ steps.diff.outputs.diff }}
            ```

  success:
    if: ${{ !cancelled() }}
    name: Flux Local - Success
    needs: ['test', 'diff']
    runs-on: ubuntu-slim
    timeout-minutes: 5
    steps:
      - name: Any jobs failed?
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

      - name: All jobs passed or skipped?
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: echo "All jobs passed or skipped" && echo "${{ toJSON(needs.*.result) }}"
