---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: 'Renovate'

on:
  workflow_dispatch:

  schedule:
    - cron: '1 * * * *' # Every hour (1min post the hour)
  push:
    branches: ['main']
    paths:
      - .github/renovate.json
      - .github/renovate/**.json

permissions:
  packages: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  LOG_LEVEL: 'debug'
  RENOVATE_AUTODISCOVER: true
  RENOVATE_AUTODISCOVER_FILTER: '${{ github.repository }}'
  RENOVATE_PLATFORM: github
  RENOVATE_PLATFORM_COMMIT: true
  RENOVATE_BOT_NAME: 'bb-17'
  RENOVATE_HOST_RULES: | # private registries/repos
    [{"hostType": "docker", "matchHost": "ghcr.io", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}"}]

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-24.04
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v2.0.6
        id: app-token
        with:
          app-id: '${{ secrets.BOT_APP_ID }}'
          private-key: '${{ secrets.BOT_PRIVATE_KEY }}'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: '${{ steps.app-token.outputs.token }}'

      - name: Renovate
        uses: renovatebot/github-action@v43.0.5
        with:
          configurationFile: .github/renovate.json
          token: '${{ steps.app-token.outputs.token }}'
