---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Sync labels
on:
  push:
    paths: ['.github/labels.yaml']
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  labels:
    name: Label Sync
    runs-on: ubuntu-slim
    timeout-minutes: 10
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: sync-labels
        uses: EndBug/label-sync@52074158190acb45f3077f9099fea818aa43f97a # v2.3.3
        with:
          config-file: .github/labels.yaml
          delete-other-labels: true
          token: ${{ secrets.GITHUB_TOKEN }}
