---
metrics:
  - name: talos_version
    query: node_os_info{name="Talos"}
    label: version_id

  - name: kubernetes_version
    query: kubernetes_build_info{service="kubernetes"}
    label: git_version

  - name: cluster_node_count
    query: count(count by (node) (kube_node_status_condition{condition="Ready"}))
    colors:
      - { color: cba6f7, min: 0, max: 9999 }

  - name: cluster_pod_count
    query: sum(kube_pod_status_phase{phase="Running"})
    colors:
      - { color: cba6f7, min: 0, max: 9999 }

  - name: cluster_cpu_usage
    query: round(avg(instance:node_cpu_utilisation:rate5m) * 100, 0.1)
    suffix: "%"
    colors:
      - { color: a6e3a1, min: 0, max: 20 }
      - { color: fab387, min: 21, max: 75 }
      - { color: f38ba8, min: 76, max: 9999 }

  - name: cluster_memory_usage
    query: round(sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes) * 100, 0.1)
    suffix: "%"
    colors:
      - { color: a6e3a1, min: 0, max: 20 }
      - { color: fab387, min: 21, max: 75 }
      - { color: f38ba8, min: 76, max: 9999 }

  - name: cluster_uptime_days
    query: round(avg(node_time_seconds - node_boot_time_seconds) / 86400, 0.1)
    suffix: "d"
    colors:
      - { color: cba6f7, min: 0, max: 9999 }

  - name: ceph_health_status
    query: ceph_health_status
    colors:
      - { valueOverride: 'Healthy', color: a6e3a1, min: 0, max: 0 }
      - { valueOverride: 'Warning', color: fab387, min: 1, max: 1 }
      - { valueOverride: 'Error', color: f38ba8, min: 2, max: 2 }