---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: l1nkr
  namespace: external
  labels:
    app: l1nkr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: l1nkr
  template:
    metadata:
      labels:
        app: l1nkr
    spec:
      containers:
        - image: ghcr.io/chrede88/l1nkrdocker:v2.0.1
          name: l1nkr
          ports:
            - name: web
              containerPort: 8080
            - name: metrics
              containerPort: 2019
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ['ALL']
            seccompProfile:
              type: RuntimeDefault
      imagePullSecrets:
        - name: ghcr-secret
