---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.32.2/deployment-apps-v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name l1nkr
  namespace: external
  labels:
    app: *name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *name
  template:
    metadata:
      labels:
        app: *name
    spec:
      containers:
        - image: ghcr.io/chrede88/l1nkrdocker:v2.0.1
          name: *name
          ports:
            - name: web
              containerPort: 8080
            - name: metrics
              containerPort: 2019
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ['ALL']
            seccompProfile:
              type: RuntimeDefault
      imagePullSecrets:
        - name: ghcr-pull-secret
