---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.32.2/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: l1nkr-web-svc
  namespace: external
spec:
  selector:
    app: l1nkr
  ports:
    - name: http
      targetPort: 8080
      port: 8080
